// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen.Python
{
    using Microsoft.Agents.AI.Workflows.Declarative.Extensions;
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplatingFilePreprocessor", "1.0.0.0")]
    internal partial class PythonProviderTemplate : PythonCodeTemplate
    {
        public override string TransformText()
        {
            this.Write("# ------------------------------------------------------------------------------\n");
            this.Write("# <auto-generated>\n");
            this.Write("#     This code was generated by a tool.\n");
            this.Write("# </auto-generated>\n");
            this.Write("# ------------------------------------------------------------------------------\n\n");
            this.Write("from typing import Callable, Optional, TypeVar, List\n");
            this.Write("from datetime import datetime, timedelta\n");
            this.Write("from agents.workflows import (\n");
            this.Write("    Workflow, WorkflowBuilder, RootExecutor, ActionExecutor,\n");
            this.Write("    AgentExecutor, DelegateExecutor, FormulaSession\n");
            this.Write(")\n");
            this.Write("from agents.workflows.declarative import DeclarativeWorkflowOptions\n");
            this.Write("from extensions.ai import ChatMessage, ChatRole, AgentRunResponse, AgentRunResponseEvent\n");
            this.Write("import asyncio\n\n");
            this.Write("TInput = TypeVar('TInput')\n");
            
            if (this.Namespace is not null)
            {
                this.Write("\n# Module: ");
                this.Write(this.ToStringHelper.ToStringWithCulture(this.Namespace));
                this.Write("\n");
            }
            
            this.Write("\nclass ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Prefix ?? string.Empty));
            this.Write("WorkflowProvider:\n");
            this.Write("    \"\"\"\n");
            this.Write("    This class provides a factory method to create a Workflow instance.\n\n");
            this.Write("    The workflow defined here was generated from a declarative workflow definition.\n");
            this.Write("    Declarative workflows utilize Power FX for defining conditions and expressions.\n");
            this.Write("    To learn more about Power FX, see:\n");
            this.Write("    https://learn.microsoft.com/power-platform/power-fx/formula-reference-copilot-studio\n");
            this.Write("    \"\"\"\n");
            
            foreach (string executor in ByLine(this.Executors, formatGroup: true))
            {
                this.Write("    ");
                this.Write(this.ToStringHelper.ToStringWithCulture(executor));
                this.Write("\n");
            }
            
            this.Write("\n    @staticmethod\n");
            this.Write("    def create_workflow(\n");
            this.Write("        options: DeclarativeWorkflowOptions,\n");
            this.Write("        input_transform: Optional[Callable[[TInput], ChatMessage]] = None\n");
            this.Write("    ) -> Workflow:\n");
            this.Write("        \"\"\"Create and configure the workflow with all executors and edges.\"\"\"\n");
            this.Write("        # Create root executor to initialize the workflow\n");
            this.Write("        if input_transform is None:\n");
            this.Write("            input_transform = lambda message: DeclarativeWorkflowBuilder.default_transform(message)\n\n");
            this.Write("        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootInstance));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootExecutorType));
            this.Write("Executor(options=options, input_transform=input_transform)\n");
            
            foreach (string instance in ByLine(this.Instances))
            {
                this.Write("        ");
                this.Write(this.ToStringHelper.ToStringWithCulture(instance));
                this.Write("\n");
            }
            
            this.Write("\n        # Define the workflow builder\n");
            this.Write("        builder = WorkflowBuilder(root_executor=");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootInstance));
            this.Write(")\n\n");
            this.Write("        # Connect executors\n");
            
            foreach (string edge in ByLine(this.Edges))
            {
                this.Write("        ");
                this.Write(this.ToStringHelper.ToStringWithCulture(edge));
                this.Write("\n");
            }
            
            this.Write("\n        # Build the workflow\n");
            this.Write("        return builder.build()\n");
            
            return this.GenerationEnvironment.ToString();
        }
    }
}
