// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen.Python
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplatingFilePreprocessor", "1.0.0.0")]
    internal partial class PythonEdgeTemplate : PythonCodeTemplate
    {
        public override string TransformText()
        {
            if (this.Condition is not null)
            {
                this.Write("    builder.add_edge(");
                this.Write(this.ToStringHelper.ToStringWithCulture(this.SourceId));
                this.Write(", ");
                this.Write(this.ToStringHelper.ToStringWithCulture(this.TargetId));
                this.Write(", condition=lambda result: ");
                this.Write(this.ToStringHelper.ToStringWithCulture(this.Condition));
                this.Write(")");
            }
            else
            {
                this.Write("    builder.add_edge(");
                this.Write(this.ToStringHelper.ToStringWithCulture(this.SourceId));
                this.Write(", ");
                this.Write(this.ToStringHelper.ToStringWithCulture(this.TargetId));
                this.Write(")");
            }
            this.Write("\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
