// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen.Python
{
    using Microsoft.Agents.AI.Workflows.Declarative.Extensions;
    using Microsoft.Agents.AI.Workflows.Declarative.Interpreter;
    using Microsoft.Bot.ObjectModel;
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplatingFilePreprocessor", "1.0.0.0")]
    internal partial class PythonRootTemplate : PythonCodeTemplate, IModeledAction
    {
        public override string TransformText()
        {
            this.Write("class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TypeName));
            this.Write("Executor(RootExecutor):\n");
            this.Write("    \"\"\"The root executor for a declarative workflow.\"\"\"\n\n");
            this.Write("    def __init__(\n");
            this.Write("        self,\n");
            this.Write("        options: DeclarativeWorkflowOptions,\n");
            this.Write("        input_transform: Callable[[TInput], ChatMessage]\n");
            this.Write("    ):\n");
            this.Write("        super().__init__(\n");
            this.Write("            id=\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Id));
            this.Write("\",\n");
            this.Write("            options=options,\n");
            this.Write("            input_transform=input_transform\n");
            this.Write("        )\n\n");
            this.Write("    async def execute_async(\n");
            this.Write("        self,\n");
            this.Write("        message: TInput,\n");
            this.Write("        context: 'IWorkflowContext',\n");
            this.Write("        cancellation_token: 'CancellationToken'\n");
            this.Write("    ) -> None:");
            
            if (this.TypeInfo.EnvironmentVariables.Count > 0)
            {
                this.Write("\n        # Set environment variables\n");
                this.Write("        await self.initialize_environment_async(\n");
                this.Write("            context,");
                
                int index = this.TypeInfo.EnvironmentVariables.Count - 1;
                foreach (string variableName in this.TypeInfo.EnvironmentVariables)
                {
                    this.Write("\n            \"");
                    this.Write(this.ToStringHelper.ToStringWithCulture(variableName));
                    this.Write("\"");
                    this.Write(this.ToStringHelper.ToStringWithCulture(index > 0 ? "," : ""));
                    --index;
                }
                
                this.Write("\n        )");
            }
            
            if (this.TypeInfo.UserVariables.Count > 0)
            {
                this.Write("\n        # Initialize variables");
                
                foreach (VariableInformationDiagnostic variableInfo in this.TypeInfo.UserVariables)
                {
                    this.Write("\n        await context.queue_state_update_async(\n");
                    this.Write("            key=\"");
                    this.Write(this.ToStringHelper.ToStringWithCulture(variableInfo.Path.VariableName));
                    this.Write("\",\n");
                    this.Write("            value=UnassignedValue.instance(),\n");
                    this.Write("            scope_name=\"");
                    this.Write(this.ToStringHelper.ToStringWithCulture(variableInfo.Path.NamespaceAlias));
                    this.Write("\"\n");
                    this.Write("        )");
                }
            }
            
            this.Write("\n\n");
            
            return this.GenerationEnvironment.ToString();
        }
    }
}
