// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen.Python
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplatingFilePreprocessor", "1.0.0.0")]
    internal partial class PythonInstanceTemplate : PythonCodeTemplate
    {
        public override string TransformText()
        {
            this.Write(this.ToStringHelper.ToStringWithCulture(this.InstanceVariable));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ExecutorType));
            this.Write("Executor(session=");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootVariable));
            this.Write(".session");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.HasProvider ? ", agent_provider=options.agent_provider" : ""));
            this.Write(")\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
