// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Agents.AI.Workflows.Declarative.CodeGen.Python
{
    using Microsoft.Agents.AI.Workflows.Declarative.Interpreter;
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("TextTemplatingFilePreprocessor", "1.0.0.0")]
    internal partial class PythonEmptyTemplate : PythonCodeTemplate, IModeledAction
    {
        public override string TransformText()
        {
            this.Write(this.ToStringHelper.ToStringWithCulture(this.InstanceVariable));
            this.Write(" = DelegateExecutor(id=\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Id));
            this.Write("\", session=");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.RootVariable));
            this.Write(".session");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Action is not null ? $", delegate={this.Action}" : ""));
            this.Write(")\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
